# Generated by Django 4.0 on 2023-11-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_map', '0003_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_number',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
