# Generated by Django 4.0 on 2023-12-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_map', '0004_model_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='desc',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
