# Generated by Django 4.0 on 2023-12-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_map', '0005_salesorder_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='desc',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
