# Generated by Django 4.0 on 2023-12-12 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_map', '0006_purchaseorder_amount_purchaseorder_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route_map.workorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route_map.workorder'),
        ),
    ]
