# Generated by Django 4.0 on 2023-12-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_map', '0007_alter_purchaseorder_work_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paypal_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
