# Generated by Django 4.0 on 2023-12-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_map', '0009_customer_phone_customer_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
